//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System.ServiceModel;
using System.ServiceModel.Channels;
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IVideoChatRoom")]
public interface IVideoChatRoom
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoChatRoom/SendWebcamCapture", ReplyAction="http://tempuri.org/IVideoChatRoom/SendWebcamCaptureResponse")]
    void SendWebcamCapture(byte[] capture);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoChatRoom/SendMicrophoneCapture", ReplyAction="http://tempuri.org/IVideoChatRoom/SendMicrophoneCaptureResponse")]
    void SendMicrophoneCapture(byte[] capture);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoChatRoom/InitializeForm", ReplyAction="http://tempuri.org/IVideoChatRoom/InitializeFormResponse")]
    void InitializeForm();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IVideoChatRoomChannel : IVideoChatRoom, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class VideoChatRoomClient : ClientBase<IVideoChatRoom>, IVideoChatRoom
{
    
    public VideoChatRoomClient()
    {

    }
    
    public VideoChatRoomClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public VideoChatRoomClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VideoChatRoomClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public VideoChatRoomClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {

    }
    
    public void SendWebcamCapture(byte[] capture)
    {
        base.Channel.SendWebcamCapture(capture);
    }
    
    public void SendMicrophoneCapture(byte[] capture)
    {
        base.Channel.SendMicrophoneCapture(capture);
    }
    
    public void InitializeForm()
    {
        base.Channel.InitializeForm();
    }
}
