using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace UIControls
{
    public partial class IdentityControl : UserControl
    {
        #region private members

        #endregion

        #region c-tor

        public IdentityControl()
        {
            InitializeComponent();
        }

        #endregion

        #region event callbacks

        private void txtMyID_KeyDown(object sender, KeyEventArgs e)
        {
            int lengthBeforeUpdate = txtMyID.Text.Length;
            MessageBox.Show("Autogenerated property!", "Permission denied", MessageBoxButtons.OK, MessageBoxIcon.Information);
            int lengthAfterUpdate = txtMyID.Text.Length;
            if (lengthAfterUpdate > lengthBeforeUpdate)
            {
                txtMyID.Text = txtMyID.Text.Substring(0, txtMyID.Text.Length - 1);
            }
        }

        #endregion


        #region private methods

       

        #endregion
    }
}
