//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System.ServiceModel;
using System.ServiceModel.Channels;
using GenericDataLayer;

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MViewerClient : ClientBase<IMViewerService>, IMViewerService
{
    
    public MViewerClient()
    {

    }
    
    public MViewerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MViewerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MViewerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MViewerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {

    }
    
    public void SendWebcamCapture(byte[] capture)
    {
        base.Channel.SendWebcamCapture(capture);
    }
    
    public void SendMicrophoneCapture(byte[] capture)
    {
        base.Channel.SendMicrophoneCapture(capture);
    }
    
    public void InitializeForm()
    {
        base.Channel.InitializeForm();
    }
}
